spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm
    time-zone: UTC
  application:
    name: can-taxi
  security:
    user:
      name: user
      password: user
  datasource:
    username: postgres
    password: 12345
    url: jdbc:postgresql://localhost:5432/can-taxi
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update